MEN - Z17 MDIS Driver - z17_drv.c File Reference
Z17 MDIS Driver
z17_drv.c File Reference
z17_drv.c File Reference
Low-level driver for the 16Z034, 16Z037 and 16Z127 GPIO controller.
Data Structures
struct LL_HANDLE
low-level handle
Macros
#define _NO_LL_HANDLE /* ll_defs.h: don't define LL_HANDLE struct */
#define CH_NUMBER 1
number of device channels
#define USE_IRQ TRUE
interrupt required
#define ADDRSPACE_COUNT 1
nbr of required address spaces
#define ADDRSPACE_SIZE 0x20
size of address space for all other GPIOs
#define DBG_MYLEVEL llHdl->dbgLevel
debug level
#define DBH llHdl->dbgHdl
debug handle
#define OSH llHdl->osHdl
OS handle.
#define TOG_TIME_DEFAULT 1000
default toggle time [ms]
#define TOG_TIME_MIN 100
min toggle time (100ms)
#define TOG_TIME_MAX 60000
max toggle time (1min)
#define TOG_CYCLIC 1
endless timer flag
#define RESET_DEFAULT 0
default arwen reset (enabled)
#define RESET_OFF 1
disables the arwen reset function
Functions
static int32 Z17_Init (DESC_SPEC *descP, OSS_HANDLE *osHdl, MACCESS *ma, OSS_SEM_HANDLE *devSemHdl, OSS_IRQ_HANDLE *irqHdl, LL_HANDLE **llHdlP)
Allocate and return low-level handle, initialize hardware.
static int32 Z17_Exit (LL_HANDLE **llHdlP)
De-initialize hardware and clean up memory.
static int32 Z17_Read (LL_HANDLE *llHdl, int32 ch, int32 *valueP)
Read a value from the device.
static int32 Z17_Write (LL_HANDLE *llHdl, int32 ch, int32 value)
Description: Write a value to the device.
static int32 Z17_SetStat (LL_HANDLE *llHdl, int32 code, int32 ch, INT32_OR_64 value32_or_64)
Set the driver status.
static int32 Z17_GetStat (LL_HANDLE *llHdl, int32 code, int32 ch, INT32_OR_64 *value32_or_64P)
Get the driver status.
static int32 Z17_BlockRead (LL_HANDLE *llHdl, int32 ch, void *buf, int32 size, int32 *nbrRdBytesP)
Read a data block from the device.
static int32 Z17_BlockWrite (LL_HANDLE *llHdl, int32 ch, void *buf, int32 size, int32 *nbrWrBytesP)
Write a data block from the device.
static int32 Z17_Irq (LL_HANDLE *llHdl)
Interrupt service routine.
static int32 Z17_Info (int32 infoType,...)
Get information about hardware and driver requirements.
static char * Ident (void)
Return ident string.
static int32 Cleanup (LL_HANDLE *llHdl, int32 retCode)
Close all handles, free memory and return error code.
static void arwenReset (LL_HANDLE *llHdl)
Reset GPIO controller.
static void AlarmHandler (void *arg)
Alarm handler.
void __Z17_GetEntry (LL_ENTRY *drvP)
Initialize driver's jump table.
Detailed Description
Low-level driver for the 16Z034, 16Z037 and 16Z127 GPIO controller.
Author
ulric.nosp@m.h.bo.nosp@m.gensp.nosp@m.erge.nosp@m.r@men.nosp@m..de
Date
2016/07/13 10:09:33
Revision
1.12
Required: OSS, DESC, DBG libraries
Preprocessor Switches:
ONE_NAMESPACE_PER_DRIVER Z17_MODEL_Z127 Z127_NOIRQ
Definition in file z17_drv.c.
Macro Definition Documentation
#define _NO_LL_HANDLE /* ll_defs.h: don't define LL_HANDLE struct */
Definition at line 83 of file z17_drv.c.
#define ADDRSPACE_COUNT 1
nbr of required address spaces
Definition at line 120 of file z17_drv.c.
Referenced by Z17_Info().
#define ADDRSPACE_SIZE 0x20
size of address space for all other GPIOs
Definition at line 121 of file z17_drv.c.
Referenced by Z17_Info().
#define CH_NUMBER 1
number of device channels
Definition at line 109 of file z17_drv.c.
Referenced by Z17_GetStat().
#define DBG_MYLEVEL llHdl->dbgLevel
debug level
Definition at line 125 of file z17_drv.c.
Referenced by Z17_Init().
#define DBH llHdl->dbgHdl
debug handle
Definition at line 126 of file z17_drv.c.
Referenced by AlarmHandler(), Cleanup(), Z17_BlockRead(), Z17_BlockWrite(), Z17_Exit(), Z17_GetStat(), Z17_Init(), Z17_Irq(), Z17_Read(), Z17_SetStat(), and Z17_Write().
#define OSH llHdl->osHdl
OS handle.
Definition at line 127 of file z17_drv.c.
Referenced by Z17_GetStat(), Z17_Irq(), and Z17_SetStat().
#define RESET_DEFAULT 0
default arwen reset (enabled)
Definition at line 136 of file z17_drv.c.
Referenced by Z17_Init().
#define RESET_OFF 1
disables the arwen reset function
Definition at line 137 of file z17_drv.c.
#define TOG_CYCLIC 1
endless timer flag
Definition at line 133 of file z17_drv.c.
Referenced by Z17_SetStat().
#define TOG_TIME_DEFAULT 1000
default toggle time [ms]
Definition at line 130 of file z17_drv.c.
Referenced by Z17_Init().
#define TOG_TIME_MAX 60000
max toggle time (1min)
Definition at line 132 of file z17_drv.c.
Referenced by Z17_SetStat().
#define TOG_TIME_MIN 100
min toggle time (100ms)
Definition at line 131 of file z17_drv.c.
Referenced by AlarmHandler(), and Z17_SetStat().
#define USE_IRQ TRUE
interrupt required
Definition at line 113 of file z17_drv.c.
Referenced by Z17_Info().
Function Documentation
void __Z17_GetEntry (LL_ENTRY * drvP)
Initialize driver's jump table.
Parameters
drvP OUT pointer to the initialized jump table structure
Definition at line 224 of file z17_drv.c.
References Z17_BlockRead(), Z17_BlockWrite(), Z17_Exit(), Z17_GetStat(), Z17_Info(), Z17_Init(), Z17_Irq(), Z17_Read(), Z17_SetStat(), and Z17_Write().
static void AlarmHandler (void * arg) static
Alarm handler.
Callback function for toggle mode
Parameters
arg IN low-level handle
Definition at line 1338 of file z17_drv.c.
References DBH, LL_HANDLE::devSemHdl, LL_HANDLE::ma, LL_HANDLE::osHdl, TOG_TIME_MIN, LL_HANDLE::togBitMask, LL_HANDLE::togCount, LL_HANDLE::togHigh, LL_HANDLE::togtimeHigh, and LL_HANDLE::togtimeLow.
Referenced by Z17_Init().
static void arwenReset (LL_HANDLE * llHdl) static
Reset GPIO controller.
Sets the controller registers to default values:
all interrupt disabled
all ports are inputs
open drain and debouncing disabled
Parameters
llHdl IN low-level handle
Definition at line 1313 of file z17_drv.c.
References LL_HANDLE::ma.
Referenced by Z17_Exit(), and Z17_Init().
static int32 Cleanup (LL_HANDLE * llHdl, int32 retCode) static
Close all handles, free memory and return error code.
Warning
The low-level handle is invalid after this function is called.
Parameters
llHdl IN low-level handle
retCode IN return value
Returns
IN retCode
Definition at line 1274 of file z17_drv.c.
References LL_HANDLE::alarmHdl, DBH, LL_HANDLE::descHdl, LL_HANDLE::memAlloc, and LL_HANDLE::osHdl.
Referenced by Z17_Exit(), and Z17_Init().
static char * Ident (void) static
Return ident string.
Returns
pointer to ident string
Definition at line 1250 of file z17_drv.c.
Referenced by Z17_Init().
static int32 Z17_BlockRead (LL_HANDLE * llHdl, int32 ch, void * buf, int32 size, int32 * nbrRdBytesP) static
Read a data block from the device.
Parameters
llHdl IN low-level handle
ch IN current channel
buf IN data buffer
size IN data buffer size
nbrRdBytesP OUT number of read bytes
Returns
0 on success or error code
Definition at line 989 of file z17_drv.c.
References DBH.
Referenced by __Z17_GetEntry().
static int32 Z17_BlockWrite (LL_HANDLE * llHdl, int32 ch, void * buf, int32 size, int32 * nbrWrBytesP) static
Write a data block from the device.
Parameters
llHdl IN low-level handle
ch IN current channel
buf IN data buffer
size IN data buffer size
nbrWrBytesP OUT number of written bytes
Returns
0 on success or error code
Definition at line 1016 of file z17_drv.c.
References DBH.
Referenced by __Z17_GetEntry().
static int32 Z17_Exit (LL_HANDLE ** llHdlP) static
De-initialize hardware and clean up memory.
The function deinitializes all channels by setting them as inputs. The interrupt is disabled.
Parameters
llHdlP IN pointer to low-level driver handle
Returns
0 on success or error code
Definition at line 395 of file z17_drv.c.
References arwenReset(), LL_HANDLE::arwenResetOff, Cleanup(), and DBH.
Referenced by __Z17_GetEntry().
static int32 Z17_GetStat (LL_HANDLE * llHdl, int32 code, int32 ch, INT32_OR_64 * value32_or_64P) static
Get the driver status.
The driver supports these status codes in addition to the standard codes (see mdis_api.h). Getstat Z17_IRQ_LAST_REQUEST will return the last IRQ request mask and clear it than.
Parameters
llHdl IN low-level handle
code IN status code
ch IN current channel
value32_or_64P IN pointer to block data structure (M_SG_BLOCK) for block status codes
value32_or_64P OUT data pointer or pointer to block data structure (M_SG_BLOCK) for block status codes
Returns
0 on success or error code
Definition at line 769 of file z17_drv.c.
References CH_NUMBER, LL_HANDLE::dbgLevel, DBH, LL_HANDLE::idFuncTbl, LL_HANDLE::irqCount, LL_HANDLE::irqHdl, LL_HANDLE::irqTest, LL_HANDLE::lastReq, LL_HANDLE::ma, OSH, LL_HANDLE::osHdl, LL_HANDLE::startTick, and LL_HANDLE::stopTick.
Referenced by __Z17_GetEntry().
static int32 Z17_Info (int32 infoType, ...) static
Get information about hardware and driver requirements.
The following info codes are supported:
 Code                      Description
 ------------------------  -----------------------------
 LL_INFO_HW_CHARACTER      hardware characteristics
 LL_INFO_ADDRSPACE_COUNT   nr of required address spaces
 LL_INFO_ADDRSPACE         address space information
 LL_INFO_IRQ               interrupt required
 LL_INFO_LOCKMODE          process lock mode required
The LL_INFO_HW_CHARACTER code returns all address and data modes (ORed) which are supported by the hardware (MDIS_MAxx, MDIS_MDxx).
The LL_INFO_ADDRSPACE_COUNT code returns the number of address spaces used by the driver.
The LL_INFO_ADDRSPACE code returns information about one specific address space (MDIS_MAxx, MDIS_MDxx). The returned data mode represents the widest hardware access used by the driver.
The LL_INFO_IRQ code returns whether the driver supports an interrupt routine (TRUE or FALSE).
The LL_INFO_LOCKMODE code returns which process locking mode the driver needs (LL_LOCK_xxx).
Parameters
infoType IN info code
... IN argument(s)
Returns
0 on success or error code
Definition at line 1148 of file z17_drv.c.
References ADDRSPACE_COUNT, ADDRSPACE_SIZE, and USE_IRQ.
Referenced by __Z17_GetEntry().
static int32 Z17_Init (DESC_SPEC * descP, OSS_HANDLE * osHdl, MACCESS * ma, OSS_SEM_HANDLE * devSemHdl, OSS_IRQ_HANDLE * irqHdl, LL_HANDLE ** llHdlP) static
Allocate and return low-level handle, initialize hardware.
The function initializes all channels with the definitions made in the descriptor. The interrupt is disabled.
The following descriptor keys are used:
 Descriptor key        Default          Range
 --------------------  ---------------  -------------
 DEBUG_LEVEL_DESC      OSS_DBG_DEFAULT  see dbg.h
 DEBUG_LEVEL           OSS_DBG_DEFAULT  see dbg.h
 RESET_OFF             0                0..1
Parameters
descP IN pointer to descriptor data
osHdl IN oss handle
ma IN hw access handle
devSemHdl IN device semaphore handle
irqHdl IN irq handle
llHdlP OUT pointer to low-level driver handle
Returns
0 on success or error code
Definition at line 268 of file z17_drv.c.
References AlarmHandler(), LL_HANDLE::alarmHdl, arwenReset(), LL_HANDLE::arwenResetOff, Cleanup(), DBG_MYLEVEL, LL_HANDLE::dbgLevel, DBH, LL_HANDLE::descHdl, LL_HANDLE::devSemHdl, Ident(), LL_HANDLE::idFuncTbl, LL_HANDLE::irqHdl, LL_HANDLE::ma, LL_HANDLE::memAlloc, LL_HANDLE::osHdl, RESET_DEFAULT, TOG_TIME_DEFAULT, LL_HANDLE::togBitMask, LL_HANDLE::togCount, LL_HANDLE::togHigh, LL_HANDLE::togtimeHigh, and LL_HANDLE::togtimeLow.
Referenced by __Z17_GetEntry().
static int32 Z17_Irq (LL_HANDLE * llHdl) static
Interrupt service routine.
The interrupt is triggered when one or more input ports change state. Depends on current setting via Z16_IRQ_SENSE. If the unit is requesting an interrupt, this mask will be stored for getstat Z17_IRQ_LAST_REQUEST.
If the driver can detect the interrupt's cause it returns LL_IRQ_DEVICE or LL_IRQ_DEV_NOT, otherwise LL_IRQ_UNKNOWN.
For MSI(x) it is necessary to disable all IRQs and enable them again at the end of the ISR.
Parameters
llHdl IN low-level handle
Returns
LL_IRQ_DEVICE irq caused by device LL_IRQ_DEV_NOT irq not caused by device LL_IRQ_UNKNOWN unknown
Definition at line 1052 of file z17_drv.c.
References DBH, LL_HANDLE::irqCount, LL_HANDLE::irqs2fire, LL_HANDLE::irqTest, LL_HANDLE::lastReq, LL_HANDLE::ma, OSH, LL_HANDLE::outBit, LL_HANDLE::outLast, LL_HANDLE::portChangeSig, and LL_HANDLE::stopTick.
Referenced by __Z17_GetEntry().
static int32 Z17_Read (LL_HANDLE * llHdl, int32 ch, int32 * valueP) static
Read a value from the device.
The function reads the current state of all port pins.
Parameters
llHdl IN low-level handle
ch IN current channel
valueP OUT read value
Returns
0 on success or error code
Definition at line 429 of file z17_drv.c.
References DBH, and LL_HANDLE::ma.
Referenced by __Z17_GetEntry().
static int32 Z17_SetStat (LL_HANDLE * llHdl, int32 code, int32 ch, INT32_OR_64 value32_or_64) static
Set the driver status.
The driver supports these status codes in addition to the standard codes (see mdis_api.h). Note: only inputs are able fire an interrupt
Parameters
llHdl IN low-level handle
code IN status code
ch IN current channel
value32_or_64 IN data or pointer to block data structure (M_SG_BLOCK) for block status codes
Returns
0 on success or error code
Definition at line 480 of file z17_drv.c.
References LL_HANDLE::alarmHdl, LL_HANDLE::dbgLevel, DBH, LL_HANDLE::irqCount, LL_HANDLE::irqs2fire, LL_HANDLE::irqTest, LL_HANDLE::ma, OSH, LL_HANDLE::osHdl, LL_HANDLE::outBit, LL_HANDLE::outLast, LL_HANDLE::portChangeSig, LL_HANDLE::startTick, LL_HANDLE::stopTick, TOG_CYCLIC, TOG_TIME_MAX, TOG_TIME_MIN, LL_HANDLE::togBitMask, LL_HANDLE::togtimeHigh, and LL_HANDLE::togtimeLow.
Referenced by __Z17_GetEntry().
static int32 Z17_Write (LL_HANDLE * llHdl, int32 ch, int32 value) static
Description: Write a value to the device.
The function writes a value to the ports which are programmed as outputs.
Parameters
llHdl IN low-level handle
ch IN current channel
value IN value to write
Returns
0 on success or error code
Definition at line 453 of file z17_drv.c.
References DBH, and LL_HANDLE::ma.
Referenced by __Z17_GetEntry().